name: Generate and Push CSV

on:
  workflow_dispatch:  # 手動トリガー

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies from requirements.txt
        run: |
          pip install -r requirements.txt  # requirements.txtから依存パッケージをインストール

      - name: Run Python script and generate CSV
        run: |
          python src/main.py  # CSVファイルを生成
    
      - name: Commit and push CSV to repository
        run: |
          git config --local user.email "tan0ry020204@gmail.com"
          git config --local user.name "Ry02024"
          git add output/result.csv
          git commit -m "Add generated CSV file"
          git push https://Ry02024:${{ secrets.PAT_TOKEN }}@github.com/Ry02024/ci-cd.git main
